name: Build and Publish

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:

  build-and-publish-docker-image:
    name: Build docker image and push to repository
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to GitHub Container Registry as specific tag
        uses: docker/build-push-action@v2
        if: ${{ github.ref_type == 'tag' }}
        with:
          context: ./
          platforms: linux/amd64
          tags: "ghcr.io/${{ github.repository }}:${{ github.ref_name }}"
          push: true

      - name: Build image and push to GitHub Container Registry as latest
        uses: docker/build-push-action@v2
        if: ${{ github.ref_type != 'tag' }}
        with:
          context: ./
          platforms: linux/amd64
          tags: "ghcr.io/${{ github.repository }}:latest"
          push: ${{ github.ref == 'refs/heads/main' }}
